config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "posts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: 'users/registrations' }

  resources :users, only: [:index] do
    resources :profiles
  end

  resources :posts do
    resources :comments
  end
  
  resources :friend_request, only: [:create, :index] do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  resources :likes, only: [:create] do
    member do
      delete 'delete'
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profile
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to user_profile_path(user_id: current_user, id: current_user.profile.id), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.fetch(:profile, {}).permit(:user_id, :bio, :avatar)
    end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: @profile, url: [current_user, @profile]) do |form| %>
  <% if @profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.label :bio, class: "label", value: "Update your bio:" %>
    <%= form.text_area :bio, class: "textarea" %>

    <%= form.label :avatar, class: "label", value: "Profile Photo" %>
    <%= form.file_field :avatar %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <% if profile.avatar.attached? %>
    <p>
      <strong>Profile Picture:</strong>
      <figure class="image is-128x128">
        <img class="is-rounded" src="<%=(url_for(profile.avatar))%>" width="500">
      </figure>
    </p>
  <% end %>
  
  <p>
    <strong>Bio:</strong>
    <%= profile.bio %>
  </p>

</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render "form" %>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profile %>