config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "posts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: 'users/registrations' }

  resources :users, only: [:index] do
    resources :profiles
  end

  resources :posts do
    resources :comments
  end
  
  resources :friend_request, only: [:create, :index] do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  resources :likes, only: [:create] do
    member do
      delete 'delete'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @post = Post.new
    # Add some stuff here to select only posts of friends or something
    if current_user
      @friend_ids = current_user.friend_requests_as_receiver.where(status: "accepted").map{ |request| request.requester_id } +
                    current_user.friend_requests_as_requester.where(status: "accepted").map{ |request| request.receiver_id }
      @ids = @friend_ids.push(current_user.id)

      @posts = Post.where(user_id: @ids).order(created_at: :desc).all
    end
    @comment = Comment.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_feed.html.erb
<div class="hero is-fullheight">
  <div class="hero-body has-text-centered">
    <div class="container is-max-desktop">
      <div class="box">
        <%= render 'form' %>
      </div>
      <div class="box">
        <% @posts.each do |post| %>
          <% user = User.find(post.user_id) %>
          <% time_diff = Time.now - post.created_at %>
          <div class="box is-flex is-flex-direction-column">
            <div class="is-flex is-justify-content-space-between">
              <div class="label is-flex">
                <% if user.profile.avatar.attached? %>
                  <%= button_to user_profile_path(user_id: user, id: user.profile.id),
                                method: :get, class: 'button is-ghost', params: { post_id: post.id } do %>
                    <figure class="image is-32x32">
                      <img class="is-rounded" src="<%=(url_for(user.profile.avatar))%>" width="500">
                    </figure>
                  <% end %>
                <% end %>
                <%= button_to user_profile_path(user_id: user, id: user.profile.id),
                              method: :get, class: 'button is-ghost', params: { post_id: post.id } do %>
                  <figure class="image is-32x32">
                    <%= user.name %>:
                  </figure>
                <% end %>
              </div>
              <div class="label">
                <% if time_diff < 3600 %> 
                  <%= "#{time_diff / 60}".scan(/^(\d*)\.?\d*$/)[0][0] + "m" %>
                <% elsif time_diff < 86400 %>
                  <%= "#{time_diff / 3600}".scan(/^(\d*)\.?\d*$/)[0][0] + "h" %>
                <% else %>
                  <%= "#{time_diff / 86400}".scan(/^(\d*)\.?\d*$/)[0][0] + "d" %>
                <% end %>
              </div>
            </div>
            
            <div class="box has-text-left"><%= post.body %></div>

            <div class="has-text-right">
              <% like_user_ids = post.likes.map{|l| l[:user_id]} %>
              <% if like_user_ids.include?(current_user.id) %>
                <% like = Like.where(post_id: post.id, user_id: current_user.id).first %>
                <%= button_to delete_like_path(like.id),
                          method: :delete,
                          class: 'button is-ghost' do %>
                  <i class="fa-solid fa-thumbs-up"></i>
                  <%= like_user_ids.size %>
                <% end %>
              <% else %>
                <%= button_to likes_path, method: :post, class: 'button is-ghost', params: { post_id: post.id } do %>
                  <i class="fa-regular fa-thumbs-up"></i>
                  <%= like_user_ids.size %>
                <% end %>
              <% end %>
              
            </div>

             <% post.comments.each do |comment| %>
               <% comment_user = User.find(comment.user_id) %>
               <% comment_time_diff = Time.now - comment.created_at %>
               <div class="box is-flex is-flex-direction-column">
                 <div class="is-flex is-justify-content-space-between">
                   <div class="label is-flex">
                      <% if comment_user.profile.avatar.attached? %>
                        <%= button_to user_profile_path(user_id: comment_user, id: comment_user.profile.id),
                                      method: :get, class: 'button is-ghost', params: { post_id: post.id } do %>
                          <figure class="image is-32x32">
                            <img class="is-rounded" src="<%=(url_for(comment_user.profile.avatar))%>" width="500">
                          </figure>
                        <% end %>
                      <% end %>
                      <%= button_to user_profile_path(user_id: comment_user, id: comment_user.profile.id),
                                    method: :get, class: 'button is-ghost', params: { post_id: post.id } do %>
                        <figure class="image is-32x32">
                          <%= comment_user.name %>:
                        </figure>
                      <% end %>
                   </div>
                   <div class="label">
                     <% if comment_time_diff < 3600 %> 
                       <%= "#{comment_time_diff / 60}".scan(/^(\d*)\.?\d*$/)[0][0] + "m" %>
                     <% elsif comment_time_diff < 86400 %>
                       <%= "#{comment_time_diff / 3600}".scan(/^(\d*)\.?\d*$/)[0][0] + "h" %>
                     <% else %>
                       <%= "#{comment_time_diff / 86400}".scan(/^(\d*)\.?\d*$/)[0][0] + "d" %>
                     <% end %>
                   </div>
                 </div>
                  
                 <div class="box has-text-left"><%= comment.body %></div>
               </div>
             <% end %>
             <%= render 'comments/form', :locals => {:post => post} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <% if @post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.label :body, class: "label", value: "Make a new post:" %>
    <%= form.text_area :body, class: "textarea" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <% if user_signed_in? %>
      <%= render 'feed' %>
    <% else %>
      <div class="hero is-fullheight">
        <div class="hero-body has-text-centered">
          <div class="container is-max-desktop">
            <div class="box">
              <h1 class="title">Login to Momo's Odin Facebook!</h1>
              <div class="content">The time is now: <%= Time.now %></div>

              <%= render :partial => 'devise/login' %>

              
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>