config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "posts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: 'users/registrations' }

  resources :users, only: [:index] do
    resources :profiles
  end

  resources :posts do
    resources :comments
  end
  
  resources :friend_request, only: [:create, :index] do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  resources :likes, only: [:create] do
    member do
      delete 'delete'
    end
  end
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :requester, class_name: :User
  belongs_to :receiver, class_name: :User
end

app/models/friendrequest.rb
class FriendRequest < ApplicationRecord
  belongs_to :requester, class_name: :User
  belongs_to :receiver, class_name: :User

  # belongs_to :friend_a, class_name: :User
  # belongs_to :friend_b, class_name: :User
end

app/controllers/friend_request_controller.rb
class FriendRequestController < ApplicationController
  before_action :authenticate_user!
  before_action :set_friend_request, except: [:create, :index]

  def index
    @friendRequests = FriendRequest.all
  end

  def create
    friend_request = FriendRequest.create(requester_id: current_user.id, receiver_id: params[:receiver_id], status: "pending")
    if friend_request.save
      redirect_back fallback_location: friend_request_index_path, notice: 'Friend Request sent!'
    else
      redirect_back fallback_location: friend_request_index_path, alert: "Sorry, your request could not be completed. (#{friend_request.errors.full_messages.join(', ')}.)"
    end
  end

  def confirm
    if @friend_request.receiver == current_user
      FriendRequest.create(receiver_id: @friend_request.receiver.id, requester_id: @friend_request.requester.id,
      status: "accepted")
      # FriendRequest.create(requester_id: u.id, receiver_id: new_user.id, status: "pending")
      @friend_request.destroy
      redirect_back fallback_location: friend_request_index_path, notice: 'Friend Request accepted!'
    else
      flash[:alert] = 'You are not authorized to accept this friend request.'
      redirect_to root_url
    end
  end

  def delete
    if @friend_request.receiver == current_user
      @friend_request.destroy
      redirect_back fallback_location: friend_request_index_path, notice: 'Friend Request was successfully deleted.'
    else
      flash[:alert] = 'You are not authorized to delete this friend request.'
      redirect_to root_url
    end
  end

  private

  def set_friend_request
    @friend_request = FriendRequest.find(params[:id])
  end
end

app/helpers/friend_request_helper.rb
module FriendRequestHelper
end

app/views/friend_request/index.html.erb
<%# loop across all friend requests and show them with variable friend request buttons %>


<div class="column is-4 is-offset-4">
  <div class="box">
    <table class="table">
      <thead>Friend Requests</thead>
      <% @friendRequests.each do |fr| %>
        <% if current_user == fr.receiver && fr.status != "accepted" %>
          <div class="is-flex is-justify-content-space-between is-align-content-center">
            <div class="container is-flex">
              <% if fr.requester.profile.avatar.attached? %>
                <%= button_to user_profile_path(user_id: fr.requester, id: fr.requester.profile.id),
                            method: :get, class: 'button is-ghost' do %>
                  <figure class="image is-32x32">
                    <img class="is-rounded" src="<%=(url_for(fr.requester.profile.avatar))%>" width="500">
                  </figure>
                <% end %>
              <% end %>
              <%= button_to user_profile_path(user_id: fr.requester, id: fr.requester.profile.id),
                            method: :get, class: 'button is-ghost' do %>
                <%= fr.requester.name %>
              <% end %>
            </div>
            <%= button_to delete_friend_request_path(fr),
                        method: :delete,
                        class: 'button is-ghost',
                        data: { confirm: "Delete #{fr.requester.name}'s friend request?" } do %>
              <i class="fas fa-user-times"></i>
            <% end %>
            <%= button_to confirm_friend_request_path(fr),
                        method: :post,
                        class: 'button is-ghost' do %>
              <i class="fas fa-user-check"></i>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </table>
  </div>
</div>