config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "posts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", registrations: 'users/registrations' }

  resources :users, only: [:index] do
    resources :profiles
  end

  resources :posts do
    resources :comments
  end
  
  resources :friend_request, only: [:create, :index] do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  resources :likes, only: [:create] do
    member do
      delete 'delete'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav class="navbar has-background-primary-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://github.com/greatmomo">
          <%= image_tag("GitHub-Mark-32px.png") %>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item">
            Some Option
          </a>
        </div>

        <div class="navbar-end">
          <% if user_signed_in? %>
        <%# Make this whole thing only available if logged in! %>
          <div class="navbar-item">
            <%= button_to "logout", destroy_user_session_path, method: :delete, class:"button is-warning navbar-item" %>
          </div>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="columns">
      <% if user_signed_in? %>
      <div class="column is-2 has-background-info-light">
        <section class="hero is-fullheight">
          <div class="hero-body has-text-centered">
            <div class="box">
              <% if current_user.profile.avatar.attached? %>
                <p>
                  <figure class="image is-128x128">
                    <img class="is-rounded" src="<%=(url_for(current_user.profile.avatar))%>" width="500">
                  </figure>
                </p>
              <% end %>
              <div class="container">
                <table class="table">
                  <tbody>
                    <tr>
                      <td>
                        <%= link_to "Timeline", root_path %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <%= button_to user_profile_path(user_id: current_user, id: current_user.profile.id),
                          class: 'button is-ghost',
                          method: :get do %>
                          Profile
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <%= button_to edit_user_profile_path(user_id: current_user, id: current_user.profile.id),
                          class: 'button is-ghost',
                          method: :get do %>
                          Edit Profile
                        <% end %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <%= link_to "Friend Requests", friend_request_index_path %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <%= link_to "Friends", users_path(:mode => "accepted") %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <%= link_to "Find Friends", users_path(:mode => "other") %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        My Posts
                      </td>
                    </tr>
                    <tr>
                      <td>
                        Liked Posts
                      </td>
                    </tr>
                    <tr>
                      <td>
                        New Post
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section>
      </div>
      <% end %>

      <div class="column">
        <%= yield %>
      </div>

      <% if user_signed_in? %>
      <div class="column is-2 has-background-info-light">
        <section class="hero is-fullheight">
          <div class="hero-body has-text-centered">
            <div class="box">
              <div class="container">
                <table class="table">
                  <tbody>
                    <tr>
                      <td>
                        Friend Suggestions
                      </td>
                    </tr>
                    <tr>
                      <td>
                        Friends
                      </td>
                    </tr>
                    
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section>
      </div>
      <% end %>
    </div>
  </body>
</html>